nameOverride: ""

fullnamePrefixOverride: ""

instanceOverride: ""

partOfOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: dnwsilver/k8s-watchdog
  tag: ""

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - julienne-1984.rebirthofhope.ru
  tls: []
  className: nginx
  paths:
    - /

service:
  enabled: true
  type: NodePort
  ports:
    http: 8080

containerPorts:
  http: 3000

replicaCount: 1

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

resources:
  limits:
    memory: 6Mi
    cpu: 5m
  requests:
    memory: 6Mi
    cpu: 5m

livenessProbe: {}

readinessProbe: {}

volumeMounts: []

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}

command: []

args: []

annotations: {}

vmPodScrape: {}

configMap: {}

hostAliases: []

app:
  log:
    level: info
  features: []
