{{- with (include "app.secret" . | fromYaml) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
type: Opaque
data:
{{- include "app.secret" $ | nindent 2 }}
{{- end }}
