apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-seafood-paella-filesystem
spec:
  storageClassName: ""
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/docker/arts