apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-pvc-arts
  namespace: savior-som-tam
spec:
  storageClassName: ""
  volumeName: p-som-tam-filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
