apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-pvc-arts
  namespace: savior-margarine-and-kangaroo-pie
spec:
  storageClassName: ""
  volumeName: p-margarine-and-kangaroo-pie-filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
