apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-pvc-arts
  namespace: savior-balochi-turkey-soup
spec:
  storageClassName: ""
  volumeName: p-balochi-turkey-soup-filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
