apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-pvc-arts
  namespace: savior-lotus-root-and-rabbit-pie
spec:
  storageClassName: ""
  volumeName: p-lotus-root-and-rabbit-pie-filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
