apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-pv-julienne
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/docker/arts