apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-pvc-arts
  namespace: julienne
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
