{{- with (include "app.configMap" $ | fromYaml) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
data:
{{- include "app.configMap" $ | nindent 2 }}
{{- end }}
