{{- if .Values.vmPodScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "app.fullname" . }}
  {{- with .Values.vmPodScrape.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- with .Values.vmPodScrape.podMetricsEndpoints }}
  podMetricsEndpoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
{{- end }}
