nameOverride: ""

fullnamePrefixOverride: ""

instanceOverride: ""

partOfOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: dnwsilver/k8s-manager
  tag: ""

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - rebirthofhope.ru
  tls: []
  className: nginx
  paths:
    - /

service:
  enabled: true
  type: NodePort
  ports:
    http: 8080

containerPorts:
  http: 3000

replicaCount: 1

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 256Mi
    cpu: 100m

livenessProbe: {}

readinessProbe: {}

volumeMounts: []

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}

command: []

args: []

annotations: {}

vmPodScrape: {}

configMap: {}

hostAliases: []

app:
  environment: staging
  db: ""
