#!/bin/bash

API_CONFIG=environments/production-app/api.yaml.gotmpl
UIX_CONFIG=environments/production-app/uix.yaml.gotmpl
SEC_CONFIG=environments/production-app/secrets.yaml

function finish () {
  https --quiet --ignore-stdin --raw "$CALL" POST rebirthofhope.ru/api/finish/$1;
}

# 03 RESOURCE
if grep -q "memory: 8Mi" $API_CONFIG; then
  finish resources
  RESOURCE=true
fi

# 04 LOGS
if grep -q "level: info" $API_CONFIG; then
  finish logs
  LOGS=true
fi

# 05 SECRETS
SECRET=$(helm secrets decrypt ./environments/production-app/secrets.yaml | yq --raw-output '.app.db')

if [[ $SECRET == mongodb://bestserverever:27017 ]]; then
  finish secrets
  SECRETS=true
fi

# 06 REPLICA
if grep -q "replicaCount: 2" $API_CONFIG; then
  finish replicas
  REPLICA=true
fi

# 07 ENVIRONMENTS
if grep -q api.*-api.rebirthofhope.ru $UIX_CONFIG; then
  finish envs
  ENVIRONMENTS=true
fi

# 08 CORS
if grep -q origins.*uix.rebirthofhope.ru $API_CONFIG; then
  finish cors
  CORS=true
fi

# 09 INGRESS
if grep -q "extraIngress" $API_CONFIG; then
  finish ingress
  INGRESS=true
fi

# 10 VOLUMES
if grep -q "mountPath: /.output/public/arts" $UIX_CONFIG; then
  finish volume
  VOLUME=true
fi

[[ -z $RESOURCE ]]      && echo "🍄 RESOURCE"       || echo "🍀 RESOURCE"
[[ -z $LOGS ]]          && echo "🍄 LOGS"           || echo "🍀 LOGS"
[[ -z $SECRETS ]]       && echo "🍄 SECRETS"        || echo "🍀 SECRETS"
[[ -z $REPLICA ]]       && echo "🍄 REPLICA"        || echo "🍀 REPLICA"
[[ -z $ENVIRONMENTS ]]  && echo "🍄 ENVIRONMENTS"   || echo "🍀 ENVIRONMENTS"
[[ -z $CORS ]]          && echo "🍄 CORS"           || echo "🍀 CORS"
[[ -z $INGRESS ]]       && echo "🍄 INGRESS"        || echo "🍀 INGRESS"
[[ -z $VOLUME ]]        && echo "🍄 VOLUME"         || echo "🍀 VOLUMES"
